--CREATE A NEW DATABASE
CREATE DATABASE hbtn_0d_2;
--CREATE NEW USER 
CREATE USER IF NOT EXISTS 'user_0d_2'@'loacalhost' IDENTIFIED BY 'user_0d_2_pwd';
--GRANT SELECT PRIVILEGE
GRANT SELECT ON hbtn_0d_2.* TO 'user_0d_2'@'loacalhost'
--FLUSH
FLUSH PRIVILEGES;
